global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cadvisor"  # Pull the metrics from datasource: http://cadvisor:8080/metrics
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]
