# curl http://localhost
# curl http://web1.docker.localhost
# curl http://web2.docker.localhost
# https://www.kubecost.com/kubernetes-devops-tools/traefik-vs-nginx/#configuring-traefik-vs-nginx-7
# TODO: https://stackoverflow.com/questions/39420613/can-nginx-do-tcp-load-balance-with-ssl-termination
version : "3"
services :
  nginx-proxy:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  web1:
    image: python:3.10
    ports:
      - 8001:8000
    volumes:
      - ./app.py:/app/app.py
    command: |
      python3 /app/app.py -p 8000

  web2:
    image: python:3.10
    ports:
      - 8002:8000
    volumes:
      - ./app.py:/app/app.py
    command: |
      python3 /app/app.py -p 8000