version: "3"

services:
  web:
    image: webapp:${TAG:-dev}
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache

  db:
    image: postgres:16.2

  cache:
    image: redis:7.2.4